import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowUpRight, Banknote, CheckCircle2, CircleDollarSign, ClipboardList, FileCheck2, Plus, RefreshCw, Search, Send, UsersRound, X } from "lucide-react";
import { dataverse } from "./lib/dataverse";
import { createLotSnapshot, eligibleServices, groupMonthly, money, paymentTotals, validateFavorecido } from "./domain/payment";

const months = ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez"];
const statusLabel = { 100000000: "Rascunho", 100000001: "Falha no envio", 100000002: "Aguardando pagamento", 100000003: "Pago" };

function Badge({ status }) { return <span className={`status-badge status-${status}`}>{statusLabel[status] || status}</span>; }
function Metric({ tone, icon: Icon, label, value, note }) { return <article className={`metric-card tone-${tone}`}><div className="metric-icon"><Icon size={20} /></div><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></article>; }
function Drawer({ title, subtitle, children, onClose, wide = false }) { return <div className="drawer-layer"><button className="drawer-backdrop" aria-label="Fechar" onClick={onClose} /><section className={`drawer ${wide ? "wide" : ""}`} role="dialog" aria-modal="true" aria-label={title}><header><div><span>{subtitle}</span><h2>{title}</h2></div><button className="icon-button" onClick={onClose} aria-label="Fechar"><X size={20} /></button></header><div className="drawer-body">{children}</div></section></div>; }

function App() {
  const [services, setServices] = useState([]); const [favorecidos, setFavorecidos] = useState([]); const [lots, setLots] = useState([]);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const [year, setYear] = useState(new Date().getFullYear()); const [search, setSearch] = useState(""); const [filterFavorecido, setFilterFavorecido] = useState("all"); const [drawer, setDrawer] = useState(null);

  async function refresh() { setLoading(true); setError(""); try { const [serviceRows, favorecidoRows, lotRows] = await Promise.all([dataverse.listServices(), dataverse.listFavorecidos(), dataverse.listAll("cr40f_pagamentoaterceiro")]); setServices(serviceRows); setFavorecidos(favorecidoRows); setLots(lotRows); } catch (err) { setError(err.message); } finally { setLoading(false); } }
  useEffect(() => { refresh(); }, []);
  useEffect(() => { if (!notice) return undefined; const timer = setTimeout(() => setNotice(""), 3500); return () => clearTimeout(timer); }, [notice]);

  const yearServices = useMemo(() => services.filter((service) => new Date(service.dataServico).getFullYear() === Number(year)), [services, year]);
  const totals = useMemo(() => paymentTotals(yearServices), [yearServices]);
  const monthly = useMemo(() => groupMonthly(yearServices, year), [yearServices, year]);
  const eligible = useMemo(() => eligibleServices(services, filterFavorecido === "all" ? "" : filterFavorecido).filter((service) => !search || `${service.identificador} ${service.cliente} ${service.trajeto} ${service.motorista}`.toLowerCase().includes(search.toLowerCase())), [services, filterFavorecido, search]);
  const missing = yearServices.filter((service) => !service.valorCobrado || !service.valorRepasse).length;

  async function handleCreateFavorecido(form) { setSaving(true); try { await dataverse.createFavorecido(form); setNotice("Terceiro Favorecido cadastrado."); setDrawer(null); await refresh(); } catch (err) { setError(err.message); } finally { setSaving(false); } }
  async function handleCreateLot(favorecido, selected) { setSaving(true); try { const snapshot = createLotSnapshot(favorecido, selected, year); const created = await dataverse.createPayment({ ...snapshot, favorecido, favorecidoId: favorecido.id }); setNotice(`Lote ${created.identifier || "criado"} reservado.`); setDrawer(null); await refresh(); } catch (err) { setError(err.message); } finally { setSaving(false); } }
  async function handleSend(lot) { setSaving(true); try { await dataverse.sendPayment(lot, lot.version > 1 ? "reenviar" : "enviar"); setNotice("Documento enviado para geração e notificação."); setDrawer(null); await refresh(); } catch (err) { setError(err.message); } finally { setSaving(false); } }
  async function handlePaid(lot, proofUrl) { setSaving(true); try { await dataverse.markPaid(lot, proofUrl); setNotice("Pagamento registrado."); setDrawer(null); await refresh(); } catch (err) { setError(err.message); } finally { setSaving(false); } }

  if (!dataverse.available) return <main className="connection-error"><AlertTriangle size={38} /><h1>Pagamentos a Terceiros</h1><p>Abra este web resource dentro do model-driven app para conectar ao Dataverse.</p></main>;
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand-block"><div className="brand-mark"><Banknote size={21} /></div><div><strong>Betinhos</strong><span>Financeiro operacional</span></div></div><nav className="main-nav"><button className="active"><CircleDollarSign size={17} />Pagamentos</button><button onClick={() => setDrawer({ type: "lot" })}><ClipboardList size={17} />Lotes de pagamento</button><button onClick={() => setDrawer({ type: "favorecido" })}><UsersRound size={17} />Terceiros Favorecidos</button></nav><button className="primary-button sidebar-create" onClick={() => setDrawer({ type: "lot" })}><Plus size={16} />Novo lote</button><div className="sidebar-foot"><span className={`connection-dot ${dataverse.mockMode ? "mock" : ""}`} /><div><strong>{dataverse.environmentLabel}</strong><span>{dataverse.mockMode ? "modo de prévia" : "Dataverse conectado"}</span></div></div></aside>
    <main className="app-main"><header className="mobile-header"><div className="brand-mark"><Banknote size={18} /></div><strong>Pagamentos a Terceiros</strong><button className="icon-button" onClick={refresh} aria-label="Atualizar"><RefreshCw size={17} className={loading ? "spin" : ""} /></button></header><div className="content-wrap"><div className="desktop-actions"><span className="environment-pill">{dataverse.environmentLabel}</span><button className="icon-button" onClick={refresh}><RefreshCw size={15} className={loading ? "spin" : ""} />Atualizar</button></div>
      <section className="page-section"><div className="page-title"><div><span>Financeiro / Operação</span><h1>Pagamentos a Terceiros</h1><p>Consolide repasses, preserve o histórico e envie o documento certo.</p></div><button className="primary-button" onClick={() => setDrawer({ type: "lot" })}><Plus size={16} />Novo lote</button></div>
      {error && <div className="global-alert error"><AlertTriangle size={17} /><span>{error}</span><button onClick={() => setError("")}>×</button></div>}{notice && <div className="global-alert success"><CheckCircle2 size={17} /><span>{notice}</span></div>}
      <div className="metrics-grid"><Metric tone="blue" icon={Banknote} label="Receita dos serviços" value={money(totals.revenue)} note={`${totals.count} serviços concluídos em ${year}`} /><Metric tone="green" icon={CircleDollarSign} label="Repasse previsto" value={money(totals.repasse)} note="Campo próprio do repasse" /><Metric tone="blue" icon={ArrowUpRight} label="Margem operacional" value={money(totals.margin)} note="Receita menos repasse" /><Metric tone={missing ? "amber" : "green"} icon={AlertTriangle} label="Pendências de cadastro" value={missing} note={missing ? "Serviços sem preço ou repasse" : "Sem alertas no ano"} /></div>
      <div className="dashboard-grid"><section className="surface priority-panel"><div className="surface-head"><div><span>Visão anual</span><h2>Movimento por mês</h2></div><label className="year-select"><span>Ano</span><select value={year} onChange={(event) => setYear(event.target.value)}>{[year - 1, year, year + 1].map((value) => <option key={value}>{value}</option>)}</select></label></div><div className="monthly-table"><div className="monthly-head"><span>Mês</span><span>Serviços</span><span>Receita</span><span>Repasse</span><span>Margem</span></div>{monthly.map((row) => <div className="monthly-row" key={row.month}><strong>{months[row.month]}</strong><span>{row.count}</span><span>{money(row.revenue)}</span><span>{money(row.repasse)}</span><span>{money(row.margin)}</span></div>)}</div></section><section className="surface category-panel"><div className="surface-head"><div><span>Distribuição</span><h2>Terceiros Favorecidos</h2></div><button className="text-button" onClick={() => setDrawer({ type: "favorecido" })}>Cadastrar <ArrowUpRight size={14} /></button></div><div className="bar-list">{favorecidos.slice(0, 15).map((favorecido) => { const amount = yearServices.filter((service) => service.favorecidoId === favorecido.id).reduce((sum, service) => sum + service.valorRepasse, 0); const max = Math.max(...favorecidos.map((row) => yearServices.filter((service) => service.favorecidoId === row.id).reduce((sum, service) => sum + service.valorRepasse, 0)), 1); return <div className="bar-row" key={favorecido.id}><div><span>{favorecido.nome}</span><strong>{money(amount)}</strong></div><div className="bar-track"><span style={{ transform: `scaleX(${amount / max})` }} /></div></div>; })}{!favorecidos.length && <div className="empty-small">Nenhum Terceiro Favorecido ativo.</div>}</div></section></div>
      <section className="surface filter-surface"><div className="search-box"><Search size={17} /><input placeholder="Buscar serviço, cliente, trajeto ou motorista" value={search} onChange={(event) => setSearch(event.target.value)} /></div><div className="filter-grid"><label><span>Terceiro Favorecido</span><select value={filterFavorecido} onChange={(event) => setFilterFavorecido(event.target.value)}><option value="all">Todos os ativos</option>{favorecidos.map((favorecido) => <option key={favorecido.id} value={favorecido.id}>{favorecido.nome}</option>)}</select></label><label><span>Ano do serviço</span><select value={year} onChange={(event) => setYear(event.target.value)}><option>{year - 1}</option><option>{year}</option><option>{year + 1}</option></select></label><div className="filter-summary"><span>Elegíveis para lote</span><strong>{eligible.length}</strong></div><button className="secondary-button" onClick={() => setDrawer({ type: "lot" })}><Plus size={15} />Montar lote</button></div></section>
      <section className="surface table-surface"><div className="table-head"><span>Serviço</span><span>Data</span><span>Motorista</span><span>Repasse</span><span>Status</span><span /></div>{eligible.filter((service) => new Date(service.dataServico).getFullYear() === Number(year)).map((service) => <button className="service-row" key={service.id} onClick={() => setDrawer({ type: "service", service })}><div className="service-main"><span className="service-line" /><div><strong>{service.identificador}</strong><span>{service.cliente} · {service.trajeto} · {service.motorista}</span></div></div><span>{new Date(service.dataServico).toLocaleDateString("pt-BR")}</span><span>{service.motorista}</span><strong className="money-text">{money(service.valorRepasse)}</strong><Badge status={service.pagamentoId ? 100000003 : 100000000} /><ArrowUpRight size={15} /></button>)}{!eligible.length && <div className="empty-state"><FileCheck2 size={28} /><strong>Nenhum serviço elegível</strong><span>Serviços concluídos sem lote aparecerão aqui.</span></div>}</section>
      <section className="surface lots-panel"><div className="surface-head"><div><span>Rastreabilidade</span><h2>Últimos lotes</h2></div><button className="text-button" onClick={() => setDrawer({ type: "lot" })}>Novo lote <Plus size={14} /></button></div>{lots.slice(0, 5).map((lot) => <button className="lot-row" key={lot.id || lot.cr40f_pagamentoaterceiroid} onClick={() => setDrawer({ type: "lotDetail", lot })}><div><strong>{lot.identifier || lot.cr40f_identificadorlote || "Lote sem identificação"}</strong><span>{lot.favorecido?.nome || lot.cr40f_emailfavorecidoenvio || "Terceiro Favorecido"}</span></div><strong>{money(lot.repasse || lot.cr40f_totalrepasse)}</strong><Badge status={lot.status || lot.cr40f_status} /><ArrowUpRight size={15} /></button>)}{!lots.length && <div className="empty-small">Os lotes criados aparecerão nesta lista.</div>}</section>
      </section></div></main><nav className="bottom-nav" aria-label="Navegação principal"><button className="active"><CircleDollarSign size={18} /><span>Pagamentos</span></button><button onClick={() => setDrawer({ type: "lot" })}><ClipboardList size={18} /><span>Lotes</span></button><button onClick={() => setDrawer({ type: "favorecido" })}><UsersRound size={18} /><span>Terceiros</span></button></nav>{drawer?.type === "favorecido" && <FavorecidoDrawer onClose={() => setDrawer(null)} onSave={handleCreateFavorecido} saving={saving} />}{drawer?.type === "lot" && <LotDrawer favorecidos={favorecidos} services={services} year={year} onClose={() => setDrawer(null)} onSave={handleCreateLot} saving={saving} />}{drawer?.type === "lotDetail" && <LotDetailDrawer lot={drawer.lot} onClose={() => setDrawer(null)} onSend={handleSend} onPaid={handlePaid} saving={saving} />}{drawer?.type === "service" && <ServiceDetailDrawer service={drawer.service} favorecidos={favorecidos} onClose={() => setDrawer(null)} />}
  </div>;
}

function FavorecidoDrawer({ onClose, onSave, saving }) { const [form, setForm] = useState({ nome: "", tipoPessoa: "PF", documento: "", tipoChavePix: "CPF/CNPJ", chavePix: "", email: "", telefone: "" }); const [errors, setErrors] = useState({}); const set = (key, value) => setForm((current) => ({ ...current, [key]: value })); return <Drawer title="Novo Terceiro Favorecido" subtitle="Cadastro financeiro" onClose={onClose}><form className="form-stack" onSubmit={(event) => { event.preventDefault(); const validation = validateFavorecido(form); setErrors(validation); if (!Object.keys(validation).length) onSave(form); }}><div className="inline-alert"><UsersRound size={16} />O favorecido é separado do cadastro do motorista.</div><label><span>Nome ou razão social *</span><input value={form.nome} onChange={(event) => set("nome", event.target.value)} autoFocus />{errors.nome && <small className="field-error">{errors.nome}</small>}</label><div className="form-grid"><label><span>Tipo de pessoa</span><select value={form.tipoPessoa} onChange={(event) => set("tipoPessoa", event.target.value)}><option>PF</option><option>PJ</option></select></label><label><span>CPF ou CNPJ *</span><input value={form.documento} onChange={(event) => set("documento", event.target.value)} />{errors.documento && <small className="field-error">{errors.documento}</small>}</label></div><div className="form-divider"><span>Recebimento PIX</span></div><div className="form-grid"><label><span>Tipo da chave</span><select value={form.tipoChavePix} onChange={(event) => set("tipoChavePix", event.target.value)}><option>CPF/CNPJ</option><option>E-mail</option><option>Telefone</option><option>Aleatória</option></select></label><label><span>Chave PIX *</span><input value={form.chavePix} onChange={(event) => set("chavePix", event.target.value)} />{errors.chavePix && <small className="field-error">{errors.chavePix}</small>}</label></div><label><span>E-mail *</span><input type="email" value={form.email} onChange={(event) => set("email", event.target.value)} />{errors.email && <small className="field-error">{errors.email}</small>}</label><label><span>Telefone</span><input value={form.telefone} onChange={(event) => set("telefone", event.target.value)} /></label><div className="drawer-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={saving}>{saving ? <RefreshCw size={16} className="spin" /> : <CheckCircle2 size={16} />}Salvar cadastro</button></div></form></Drawer>; }

function LotDrawer({ favorecidos, services, year, onClose, onSave, saving }) { const [favorecidoId, setFavorecidoId] = useState(favorecidos[0]?.id || ""); const available = eligibleServices(services, favorecidoId); const [selected, setSelected] = useState(available.map((service) => service.id)); useEffect(() => setSelected(available.map((service) => service.id)), [favorecidoId, services.length]); const favorecido = favorecidos.find((row) => row.id === favorecidoId); const chosen = available.filter((service) => selected.includes(service.id)); const totals = paymentTotals(chosen); return <Drawer title="Montar lote" subtitle="Reserva imediata de serviços" wide onClose={onClose}><div className="form-stack"><label><span>Terceiro Favorecido</span><select value={favorecidoId} onChange={(event) => setFavorecidoId(event.target.value)}>{favorecidos.map((row) => <option key={row.id} value={row.id}>{row.nome}</option>)}</select></label><div className="lot-summary"><div><span>Serviços</span><strong>{totals.count}</strong></div><div><span>Repasse</span><strong>{money(totals.repasse)}</strong></div><div><span>Margem</span><strong>{money(totals.margin)}</strong></div></div><div className="selection-head"><div><strong>Serviços elegíveis</strong><span>Todos começam selecionados. Remova apenas exceções.</span></div><button className="text-button" onClick={() => setSelected(selected.length === available.length ? [] : available.map((service) => service.id))}>{selected.length === available.length ? "Limpar" : "Selecionar todos"}</button></div><div className="selection-list">{available.map((service) => <label className="selection-row" key={service.id}><input type="checkbox" checked={selected.includes(service.id)} onChange={() => setSelected((current) => current.includes(service.id) ? current.filter((id) => id !== service.id) : [...current, service.id])} /><div><strong>{service.identificador}</strong><span>{new Date(service.dataServico).toLocaleDateString("pt-BR")} · {service.trajeto}</span></div><b>{money(service.valorRepasse)}</b></label>)}{!available.length && <div className="empty-small">Não há serviços concluídos disponíveis para este favorecido.</div>}</div><div className="inline-alert"><AlertTriangle size={16} />Ao salvar, os serviços ficam reservados no lote. Cancelar o envio libera a seleção.</div><div className="drawer-actions"><button className="secondary-button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={!favorecido || !chosen.length || saving} onClick={() => onSave(favorecido, chosen)}>{saving ? <RefreshCw size={16} className="spin" /> : <ClipboardList size={16} />}Criar lote e reservar</button></div></div></Drawer>; }

function LotDetailDrawer({ lot, onClose, onSend, onPaid, saving }) { const [proofUrl, setProofUrl] = useState(""); const status = lot.status || lot.cr40f_status; const repasse = lot.repasse || lot.cr40f_totalrepasse || 0; return <Drawer title={lot.identifier || lot.cr40f_identificadorlote || "Detalhe do lote"} subtitle="Controle do pagamento" onClose={onClose}><div className="detail-stack"><div className="detail-hero"><div><Badge status={status} /><span>Versão {lot.version || lot.cr40f_versaoenvio || 1}</span></div><h3>{lot.favorecido?.nome || lot.cr40f_emailfavorecidoenvio || "Terceiro Favorecido"}</h3><p>Repasse consolidado de {money(repasse)}. O documento final inclui serviços, receita, repasse e margem.</p><div className="detail-meta"><span><strong>Serviços</strong>{lot.count || lot.cr40f_quantidadeservicos || "—"}</span><span><strong>E-mail</strong>{lot.favorecido?.email || lot.cr40f_emailfavorecidoenvio || "—"}</span></div></div>{status !== 100000003 && <div className="detail-card"><h3>Próxima ação</h3><div className="detail-actions"><button onClick={() => onSend(lot)} disabled={saving}><Send size={18} /><div><strong>{lot.version > 1 ? "Reenviar documento" : "Enviar documento"}</strong><span>PDF operacional + notificação ao favorecido e Financeiro</span></div><ArrowUpRight size={16} /></button><label className="proof-input"><span>Comprovante (opcional)</span><input placeholder="URL do comprovante em OneDrive" value={proofUrl} onChange={(event) => setProofUrl(event.target.value)} /></label><button onClick={() => onPaid(lot, proofUrl)} disabled={saving}><CheckCircle2 size={18} /><div><strong>Registrar como pago</strong><span>PIX confirmado. Comprovante é opcional.</span></div><ArrowUpRight size={16} /></button></div></div>}{status === 100000003 && <div className="inline-alert success-alert"><CheckCircle2 size={16} />Pagamento confirmado. O lote permanece auditável.</div>}<div className="detail-card"><h3>Contrato de automação</h3><p className="muted-copy">O Flow recebe o ID do lote e a operação, consulta o Dataverse, gera o PDF, salva no OneDrive e notifica os destinatários.</p></div></div></Drawer>; }

function ServiceDetailDrawer({ service, favorecidos, onClose }) { const favorecido = favorecidos.find((row) => row.id === service.favorecidoId); const missing = !service.valorCobrado || !service.valorRepasse; return <Drawer title={service.identificador} subtitle="Detalhe do serviço" onClose={onClose}><div className="detail-stack"><div className="detail-hero"><div><Badge status={service.pagamentoId ? 100000003 : 100000000} /><span>{new Date(service.dataServico).toLocaleDateString("pt-BR")}</span></div><h3>{service.cliente}</h3><p>{service.trajeto}</p><div className="detail-meta"><span><strong>Motorista</strong>{service.motorista}</span><span><strong>Terceiro Favorecido</strong>{favorecido?.nome || "Não vinculado"}</span><span><strong>Valor cobrado</strong>{money(service.valorCobrado)}</span><span><strong>Repasse</strong>{service.valorRepasse ? money(service.valorRepasse) : "Não definido"}</span></div></div>{missing && <div className="inline-alert"><AlertTriangle size={16} />Este serviço não pode entrar em lote enquanto preço e repasse não estiverem preenchidos.</div>}<div className="detail-card"><h3>Regra financeira</h3><p className="muted-copy">O repasse vem exclusivamente de `cr40f_valorrepasseterceiro` na composição. O valor é congelado no item do lote.</p></div></div></Drawer>; }

export default App;
